#!/usr/bin/env python3
import argparse
import json
import random
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT_DIR / "honeypots" / "fake_corp"
USERDB_PATH = ROOT_DIR / "honeypots" / "cowrie" / "userdb.txt"

FIRST_NAMES = [
    "marco", "luca", "giulia", "andrea", "francesca", "paolo", "elena",
    "stefano", "laura", "matteo", "anna", "roberto", "chiara", "davide",
]
LAST_NAMES = [
    "rossi", "bianchi", "romano", "conti", "gallo", "ferrari", "ricci",
    "marino", "greco", "bruno", "rinaldi", "costa", "moretti", "lombardi",
]
ROLES = [
    ("IT", "sysadmin"),
    ("IT", "backup-admin"),
    ("Finance", "finance-ops"),
    ("HR", "hr-operator"),
    ("DevOps", "deploy"),
    ("Sales", "crm-user"),
    ("Security", "soc-analyst"),
]
PASSWORD_PATTERNS = [
    "Winter2026!", "Spring2026!", "Backup2026!", "Welcome2026!",
    "Company2026!", "Password2026!", "ChangeMe2026!", "Vpn2026!",
]


def safe_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_users(company: str, count: int) -> list[dict]:
    users = []
    used = set()
    for index in range(count):
        first = random.choice(FIRST_NAMES)
        last = random.choice(LAST_NAMES)
        username = f"{first}.{last}"
        while username in used:
            username = f"{first}.{last}{random.randint(2, 99)}"
        used.add(username)
        department, role = random.choice(ROLES)
        password = random.choice(PASSWORD_PATTERNS)
        users.append({
            "username": username,
            "password": password,
            "department": department,
            "role": role,
            "email": f"{username}@{company.lower().replace(' ', '')}.local",
        })
    users.extend([
        {
            "username": "svc-backup",
            "password": "Backup2026!",
            "department": "IT",
            "role": "service-account",
            "email": f"svc-backup@{company.lower().replace(' ', '')}.local",
        },
        {
            "username": "deploy",
            "password": "Deploy2026!",
            "department": "DevOps",
            "role": "deployment-account",
            "email": f"deploy@{company.lower().replace(' ', '')}.local",
        },
    ])
    return users


def render_userdb(users: list[dict]) -> str:
    lines = [
        "# BEGIN HONEYPOTX FAKE CORPORATE USERS",
        "# Generated by scripts/generate_fake_corp.py",
    ]
    lines.extend(f"{user['username']}:x:{user['password']}" for user in users)
    lines.append("# END HONEYPOTX FAKE CORPORATE USERS")
    return "\n".join(lines) + "\n"


def update_cowrie_userdb(users: list[dict]) -> None:
    if USERDB_PATH.exists():
        backup = USERDB_PATH.with_suffix(f".txt.backup.{datetime.now().strftime('%Y%m%d%H%M%S')}")
        shutil.copy2(USERDB_PATH, backup)
        current = USERDB_PATH.read_text(encoding="utf-8")
    else:
        current = ""

    start = "# BEGIN HONEYPOTX FAKE CORPORATE USERS"
    end = "# END HONEYPOTX FAKE CORPORATE USERS"
    generated = render_userdb(users)
    if start in current and end in current:
        before = current.split(start, 1)[0].rstrip()
        after = current.split(end, 1)[1].lstrip()
        content = "\n".join(part for part in [before, generated.rstrip(), after.rstrip()] if part) + "\n"
    else:
        content = current.rstrip() + "\n\n" + generated if current.strip() else generated
    USERDB_PATH.write_text(content, encoding="utf-8")


def generate_files(output: Path, company: str, users: list[dict]) -> None:
    ftp_root = output / "ftp_root"
    safe_write(ftp_root / "README.txt", f"{company} internal file server\nAuthorized personnel only.\n")
    safe_write(ftp_root / "IT" / "backup" / "backup-prod.env", "\n".join([
        "APP_ENV=production",
        "DB_HOST=db-prod-01.internal",
        "DB_USER=svc-backup",
        "DB_PASS=Backup2026!",
        "S3_BUCKET=corp-prod-backups",
        "",
    ]))
    safe_write(ftp_root / "IT" / "vpn" / "vpn-users.csv", "username,department,status\n" + "\n".join(
        f"{user['username']},{user['department']},active" for user in users[:10]
    ) + "\n")
    safe_write(ftp_root / "Finance" / "Q4" / "wire-transfers.csv", "\n".join([
        "date,vendor,amount,status",
        "2026-01-12,ACME Hosting,18420.50,pending",
        "2026-01-16,Northwind Security,9280.00,approved",
        "",
    ]))
    safe_write(ftp_root / "HR" / "employees.csv", "name,email,department,role\n" + "\n".join(
        f"{user['username']},{user['email']},{user['department']},{user['role']}" for user in users
    ) + "\n")
    safe_write(ftp_root / "DevOps" / "deploy" / "deploy_notes.txt", "\n".join([
        "Deployment notes",
        "- legacy admin panel: /admin",
        "- deploy user: deploy",
        "- rotate Deploy2026! after migration",
        "",
    ]))
    safe_write(ftp_root / "Security" / "alerts" / "false_positive_notes.md", "\n".join([
        "# SOC notes",
        "- Investigate repeated login attempts against svc-backup",
        "- Monitor SQLi probes on /search and /login",
        "",
    ]))


def write_manifest(output: Path, company: str, users: list[dict]) -> None:
    manifest = {
        "company": company,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "users": users,
        "breadcrumbs": [
            "IT/backup/backup-prod.env",
            "IT/vpn/vpn-users.csv",
            "Finance/Q4/wire-transfers.csv",
            "HR/employees.csv",
            "DevOps/deploy/deploy_notes.txt",
            "Security/alerts/false_positive_notes.md",
        ],
        "notes": "All generated data is fake and intended for deception/honeypot use only.",
    }
    safe_write(output / "manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate fake corporate honeypot assets.")
    parser.add_argument("--company", default="ACME Corp", help="Fake company name")
    parser.add_argument("--users", type=int, default=14, help="Number of fake human users")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output directory")
    parser.add_argument("--seed", type=int, default=None, help="Optional deterministic random seed")
    parser.add_argument("--no-userdb", action="store_true", help="Do not update Cowrie userdb.txt")
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    users = generate_users(args.company, max(1, min(args.users, 100)))
    generate_files(args.output, args.company, users)
    write_manifest(args.output, args.company, users)
    if not args.no_userdb:
        update_cowrie_userdb(users)

    print(f"Fake corporate environment generated in: {args.output}")
    print(f"FTP root: {args.output / 'ftp_root'}")
    print(f"Manifest: {args.output / 'manifest.json'}")
    if not args.no_userdb:
        print(f"Cowrie userdb updated: {USERDB_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
