#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

ask() {
  local label="$1"
  local default="$2"
  local value
  read -r -p "$label [$default]: " value
  printf '%s' "${value:-$default}"
}

write_env() {
  local key="$1"
  local value="$2"
  printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
}

printf 'HoneypotX installer\n'
printf 'Project root: %s\n\n' "$ROOT_DIR"

if [ -f "$ENV_FILE" ]; then
  backup="$ENV_FILE.backup.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup"
  printf 'Existing .env backed up to %s\n' "$backup"
fi

default_cowrie="$ROOT_DIR/honeypots/logs/cowrie/cowrie.json"
default_opencanary="$ROOT_DIR/honeypots/logs/opencanary/opencanary.log"
default_ftp="$ROOT_DIR/honeypots/logs/ftp/ftp.json"

cowrie_log="$(ask 'Cowrie JSON log path' "$default_cowrie")"
opencanary_log="$(ask 'OpenCanary log path' "$default_opencanary")"
ftp_log="$(ask 'FTP JSON log path' "$default_ftp")"
api_host="$(ask 'API bind host' '0.0.0.0')"
api_port="$(ask 'API port' '8000')"
poll_interval="$(ask 'Polling interval seconds' '3')"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh
EOF
write_env HPX_COWRIE_LOG "$cowrie_log"
write_env HPX_OPENCANARY_LOG "$opencanary_log"
write_env HPX_FTP_LOG "$ftp_log"
write_env HPX_DB_PATH "$ROOT_DIR/data/honeypotx.db"
write_env HPX_GEO_CACHE_PATH "$ROOT_DIR/data/cache/geo_cache.json"
write_env HPX_OFFSETS_PATH "$ROOT_DIR/data/state/offsets.json"
write_env HPX_EVENTS_EXPORT_PATH "$ROOT_DIR/data/exports/events_export.json"
write_env HPX_DASHBOARD_AUTH_PATH "$ROOT_DIR/config/dashboard_auth.json"
write_env HPX_ATTACK_SETTINGS_PATH "$ROOT_DIR/config/attack_settings.json"
write_env HPX_API_HOST "$api_host"
write_env HPX_API_PORT "$api_port"
write_env HPX_FRONTEND_ORIGIN '*'
write_env HPX_POLL_INTERVAL "$poll_interval"
write_env HPX_GEO_API_BASE 'http://ip-api.com/json'

mkdir -p "$ROOT_DIR/data/cache" "$ROOT_DIR/data/exports" "$ROOT_DIR/data/state" "$ROOT_DIR/config"
touch "$cowrie_log" "$opencanary_log" "$ftp_log" 2>/dev/null || true

printf '\n.env generated: %s\n' "$ENV_FILE"

if [ ! -f "$ROOT_DIR/config/attack_settings.json" ]; then
  python3 - <<'PY'
from backend.settings import save_attack_settings
save_attack_settings({})
print('Attack settings initialized.')
PY
fi

printf '\nDashboard credentials\n'
printf 'Set or rotate the dashboard login now.\n'
python3 "$ROOT_DIR/scripts/set_dashboard_password.py"

printf '\nRunning healthcheck...\n'
"$ROOT_DIR/scripts/healthcheck.sh" || true

printf '\nInstallation complete.\n'
printf 'Start API manually with your usual command, or use run_all.py if configured.\n'
