version: "3.9"

networks:
  honeypot-net:
    driver: bridge

volumes:
  logs:

services:

  cowrie:
    build: ./cowrie
    container_name: cowrie
    user: "999:999"
    restart: unless-stopped
    ports:
      - "22:2222"    # SSH
      - "23:2223"    # Telnet
    volumes:
      - ./cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./cowrie/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
      - ./cowrie/honeyfs:/cowrie/cowrie-git/honeyfs:ro
      - ./cowrie/share/cowrie/fs.pickle:/cowrie/cowrie-git/share/cowrie/fs.pickle:ro
      - ./logs/cowrie:/cowrie/cowrie-git/var/log/cowrie
    networks:
      - honeypot-net

  opencanary:
    build: ./opencanary
    container_name: opencanary
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/opencanary:/var/log/opencanary
    networks:
      - honeypot-net

  dionaea:
    build: ./dionaea
    container_name: dionaea
    restart: unless-stopped
    ports:
      - "21:21"
      - "20:20"
    volumes:
      - ./logs/ftp:/opt/dionaea/var/log/dionaea
      - ./fake_corp/ftp_root:/opt/dionaea/fake_corp/ftp_root:ro
    networks:
      - honeypot-net

  mysql-honeypot:
    build: ./mysql
    container_name: mysql-honeypot
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./logs/mysql:/opt/honeypot/logs
    networks:
      - honeypot-net

  smb-honeypot:
    build: ./smb
    container_name: smb-honeypot
    restart: unless-stopped
    ports:
      - "445:445"
    volumes:
      - ./logs/smb:/opt/honeypot/logs
    networks:
      - honeypot-net

  scada-honeypot:
    build: ./scada
    container_name: scada-honeypot
    restart: unless-stopped
    ports:
      - "502:502"   # Modbus/TCP
      - "102:102"   # S7comm / ISO-on-TCP (Siemens S7)
    volumes:
      - ./logs/scada:/opt/honeypot/logs
    networks:
      - honeypot-net
